version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: cooking_django/Dockerfile      
    restart: always
    container_name: backend  
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  vue:
    build:
      context: .
      dockerfile: cooking_vue/Dockerfile
    restart: always
    container_name: frontend
    command: npm run serve
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - django